name: nicky
description: "App romántica hecha en Flutter para San Valentín"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  shared_preferences: ^2.5.4
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  audioplayers: ^6.1.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/nicol.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/nicol.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/nicol.png
